HELP;

USE /opt/1Tdata/xbase/xbase.30/data;

# INSERT INTO TestSQL.DBF (CITY, STATE, ZIPCODE, NOTES, LASTUPDATE, ACTIVE ) VALUES ( 'San Diego', 'CA', 92007, 'San Diego is a cool place', '1989-02-09', 'Y');

# CREATE TABLE TestSql.DBF( CHRFLD CHAR(6), DTFLD DATE, INTFLD INTEGER, SMINTFLD SMALLINT, NUMFLD NUMERIC(9,4), DECFLD DECIMAL(9,4), FLTFLD FLOAT(9,4) VCHARFLD VARCHAR, LGFLD LOGICAL ); 
# CREATE UNIQUE INDEX TestSql1.NDX ON TestSql.DBF( CHRFLD ) ASSOCIATE;

#DROP INDEX IF EXISTS TestSql1.NDX ON TestSql.DBF;

DROP TABLE IF EXISTS TestSql.DBF;


