# HELP;

USE /opt/1Tdata/xbase/xbase.30/data;

DROP TABLE IF EXISTS TestFlag.DBF;

CREATE TABLE TestFlag.DBF( C1 CHAR(1), C2 CHAR(2), C3 CHAR(3), D1 DATE, D2 DATE, D3 DATE, I1 INTEGER, I2 INTEGER, I3 INTEGER, N1 NUMERIC(9,1), N2 NUMERIC(9,2), N3 NUMERIC(9,3)); 

# CREATE INDEX TestSql2 ON TestSql2.DBF( CHRFLD );



