# HELP;

USE /opt/1Tdata/xbase/xbase.30/data;

DROP TABLE IF EXISTS TestSql2.DBF;

CREATE TABLE TestSql2.DBF( CHRFLD CHAR(100), DTFLD DATE, INTFLD INTEGER, SMINTFLD SMALLINT, NUMFLD NUMERIC(9,4), DECFLD DECIMAL(9,4), FLTFLD FLOAT(9,4)  LGFLD LOGICAL ); 

CREATE INDEX Ctag1 ON TestSql2.DBF( CHRFLD );



