# HELP;

USE /opt/1Tdata/xbase/xbase.30/data;

DROP TABLE IF EXISTS TwoTags.DBF;

CREATE TABLE TwoTags.DBF( CHRFLD1 CHAR(100), CHRFLD2 CHAR(100), DTFLD DATE, INTFLD INTEGER, SMINTFLD SMALLINT, NUMFLD NUMERIC(9,4), DECFLD DECIMAL(9,4), FLTFLD FLOAT(9,4)  LGFLD LOGICAL ); 



